# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f7c9d75c965be86cae31cd1eb095089fc51263e7958c0e79dc928cde72108c7cdf18e191919b8a41b4e4143690400c749dbd166b6f74a503d672c679202e0ee

test:
  secret_key_base: 5584fa102542754fa7a9564971fcea8b2b0784e99c4694b0fee8d8f8afa75c565c674c4e8f09cabf9d44a82c931a60574844d0988a423746ebaba8c898ce6dbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
